apiVersion: v1
kind: Service
metadata:
  name: instructlab-pipeline-metrics
  labels:
    app: instructlab-pipeline
    app.kubernetes.io/part-of: instructlab
    app.kubernetes.io/component: metrics
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app: instructlab-pipeline
    component: pipeline-server
  type: ClusterIP
