apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-stack
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/open-demos/nlit2025.git
    targetRevision: HEAD
    path: instructlab-gitops/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
