# This would normally be encrypted with SealedSecrets or SOPS
# For this example, we're using placeholders
apiVersion: v1
kind: Secret
metadata:
  name: teacher-secret
type: Opaque
data:
  api_token: WW91ckhpZGRlblRva2VuRm9yRGV2Cg==
  model_name: bWl4dHJhbAo=
  endpoint: aHR0cHM6Ly9leHRlcm5hbC10ZWFjaGVyLW1vZGVsLmRldi5leGFtcGxlLmNvbS92MQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: judge-secret
type: Opaque
data:
  api_token: WW91ckhpZGRlblRva2VuRm9yRGV2Cg==
  model_name: cHJvbWV0aGV1cwo=
  endpoint: aHR0cHM6Ly9leHRlcm5hbC1qdWRnZS1tb2RlbC5kZXYuZXhhbXBsZS5jb20vdjEK
